language: scala
sudo: required
dist: trusty
script:
  # plz is like ++ except it skips projects that are not defined for that scala version.
  - sbt "plz $TRAVIS_SCALA_VERSION test"
jdk:
  - oraclejdk8
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6
  - 2.13.0-M5
env:
  - SCALAJS_VERSION=0.6.25
matrix:
  include:
    - scala: 2.10.7
      jdk: openjdk7
before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
