language: scala
jdk:
  - oraclejdk8
sudo: required
dist: trusty
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
script: sbt "++$TRAVIS_SCALA_VERSION test"
jobs:
  include:
    - scala: 2.10.7
    - scala: 2.11.12
      before_install:
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    - scala: 2.12.8
    - scala: 2.13.0-RC1

    # Release stable release on tag push and snapshot on merge to master
    - stage: release
      script: sbt ci-release

cache:
  directories:
  - $HOME/.sbt/zinc
  - $HOME/.ivy2/cache
  - $HOME/.nvm
  - $HOME/.cache/coursier
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
